Repository javascript-tutorial/th.javascript.info, pull requests merged in 2022-10, with the labels that each got.

#102 Objects
  1-js/04-object-basics/01-object/2-hello-object/task.md
  1-js/04-object-basics/01-object/3-is-empty/solution.md
  1-js/04-object-basics/01-object/3-is-empty/task.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
  1-js/04-object-basics/01-object/article.md
Labels: needs +1

#103 Debugging in the browser
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: review needed, hacktoberfest-accepted

#104 Debugging in the browser
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: review needed

#105 การไล่โค้ด
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: review needed, hacktoberfest-accepted

#106 Logging
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: review needed

#107 สรุป
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: review needed
